//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Отдел_товар
    {
        public int id_отдела { get; set; }
        public int id_ОТ { get; set; }
        public int id_товара { get; set; }
        public decimal Кол_во_товара { get; set; }
    
        public virtual Отдел Отдел { get; set; }
        public virtual Товар Товар { get; set; }
    }
}
