//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продавец
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продавец()
        {
            this.Продавец_Товар__Выручка_ = new HashSet<Продавец_Товар__Выручка_>();
            this.Чек = new HashSet<Чек>();
        }
    
        public long id_продавца { get; set; }
        public long id_отдела { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public long id_СУ { get; set; }
        public string Дом { get; set; }
        public string Квартира { get; set; }
        public long id_магазина { get; set; }
        public string Дата_рождения { get; set; }
        public string Номер_паспорта { get; set; }
        public string Дата_выдачи { get; set; }
        public string Кто_выдал_паспорт_ { get; set; }
    
        public virtual Magazine Magazine { get; set; }
        public virtual Отдел Отдел { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продавец_Товар__Выручка_> Продавец_Товар__Выручка_ { get; set; }
        public virtual Справочник__Улица Справочник__Улица { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Чек> Чек { get; set; }
    }
}
