//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practica2020
{
    using System;
    using System.Collections.Generic;
    
    public partial class Содержимое_чека
    {
        public int id_СЧ { get; set; }
        public int id_чека { get; set; }
        public long id_товара { get; set; }
        public string Кол_во_товара { get; set; }
        public decimal Стоимость_товара { get; set; }
    
        public virtual Товар Товар { get; set; }
        public virtual Чек Чек { get; set; }
    }
}
